# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrate_spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibrateSpectrum(object):
    def setupUi(self, CalibrateSpectrum):
        CalibrateSpectrum.setObjectName("CalibrateSpectrum")
        CalibrateSpectrum.resize(741, 611)
        self.gridLayout = QtWidgets.QGridLayout(CalibrateSpectrum)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(CalibrateSpectrum)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.spectrum_plot_widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrum_plot_widget.sizePolicy().hasHeightForWidth())
        self.spectrum_plot_widget.setSizePolicy(sizePolicy)
        self.spectrum_plot_widget.setObjectName("spectrum_plot_widget")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calibration_points = QtWidgets.QTableView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_points.sizePolicy().hasHeightForWidth())
        self.calibration_points.setSizePolicy(sizePolicy)
        self.calibration_points.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.calibration_points.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.calibration_points.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.calibration_points.setObjectName("calibration_points")
        self.calibration_points.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.calibration_points)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.point_x_axis = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_x_axis.sizePolicy().hasHeightForWidth())
        self.point_x_axis.setSizePolicy(sizePolicy)
        self.point_x_axis.setMaximum(99999999)
        self.point_x_axis.setObjectName("point_x_axis")
        self.gridLayout_2.addWidget(self.point_x_axis, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.x_axis_pick = QtWidgets.QPushButton(self.groupBox)
        self.x_axis_pick.setFlat(False)
        self.x_axis_pick.setObjectName("x_axis_pick")
        self.gridLayout_2.addWidget(self.x_axis_pick, 1, 1, 1, 1)
        self.point_wavelength = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_wavelength.sizePolicy().hasHeightForWidth())
        self.point_wavelength.setSizePolicy(sizePolicy)
        self.point_wavelength.setMinimum(0.0)
        self.point_wavelength.setMaximum(1e+26)
        self.point_wavelength.setObjectName("point_wavelength")
        self.gridLayout_2.addWidget(self.point_wavelength, 3, 0, 1, 2)
        self.point_is_star = QtWidgets.QCheckBox(self.groupBox)
        self.point_is_star.setObjectName("point_is_star")
        self.gridLayout_2.addWidget(self.point_is_star, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(CalibrateSpectrum)
        QtCore.QMetaObject.connectSlotsByName(CalibrateSpectrum)

    def retranslateUi(self, CalibrateSpectrum):
        _translate = QtCore.QCoreApplication.translate
        CalibrateSpectrum.setWindowTitle(_translate("CalibrateSpectrum", "Calibrate"))
        self.groupBox.setTitle(_translate("CalibrateSpectrum", "New Calibration Point"))
        self.label.setText(_translate("CalibrateSpectrum", "x-axis"))
        self.label_2.setText(_translate("CalibrateSpectrum", "Wavelength (Å)"))
        self.x_axis_pick.setText(_translate("CalibrateSpectrum", "Pick"))
        self.point_is_star.setText(_translate("CalibrateSpectrum", "Zero (star)"))

