# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lines_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LinesDialog(object):
    def setupUi(self, LinesDialog):
        LinesDialog.setObjectName("LinesDialog")
        LinesDialog.resize(682, 523)
        self.gridLayout_2 = QtWidgets.QGridLayout(LinesDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(LinesDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.elements = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elements.sizePolicy().hasHeightForWidth())
        self.elements.setSizePolicy(sizePolicy)
        self.elements.setObjectName("elements")
        self.gridLayout.addWidget(self.elements, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lambda_from = QtWidgets.QSpinBox(self.groupBox)
        self.lambda_from.setMaximum(9999999)
        self.lambda_from.setObjectName("lambda_from")
        self.gridLayout.addWidget(self.lambda_from, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.lambda_to = QtWidgets.QSpinBox(self.groupBox)
        self.lambda_to.setMaximum(9999999)
        self.lambda_to.setObjectName("lambda_to")
        self.gridLayout.addWidget(self.lambda_to, 0, 5, 1, 1)
        self.pick_wavelengths = QtWidgets.QToolButton(self.groupBox)
        self.pick_wavelengths.setObjectName("pick_wavelengths")
        self.gridLayout.addWidget(self.pick_wavelengths, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 1)
        self.sp_types = QtWidgets.QCheckBox(self.groupBox)
        self.sp_types.setObjectName("sp_types")
        self.gridLayout.addWidget(self.sp_types, 1, 2, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 5, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.lines = QtWidgets.QTableView(LinesDialog)
        self.lines.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lines.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lines.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lines.setObjectName("lines")
        self.lines.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.lines, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(LinesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(LinesDialog)
        self.buttonBox.accepted.connect(LinesDialog.accept)
        self.buttonBox.rejected.connect(LinesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LinesDialog)

    def retranslateUi(self, LinesDialog):
        _translate = QtCore.QCoreApplication.translate
        LinesDialog.setWindowTitle(_translate("LinesDialog", "Dialog"))
        self.groupBox.setTitle(_translate("LinesDialog", "Filters"))
        self.label.setText(_translate("LinesDialog", "Element"))
        self.label_2.setText(_translate("LinesDialog", "Wavelength"))
        self.label_3.setText(_translate("LinesDialog", "to"))
        self.pick_wavelengths.setText(_translate("LinesDialog", "..."))
        self.label_4.setText(_translate("LinesDialog", "Name"))
        self.sp_types.setText(_translate("LinesDialog", "Has reference spectral classes"))
        self.pushButton.setText(_translate("LinesDialog", "Search"))

