# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/calibrate_spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibrateSpectrum(object):
    def setupUi(self, CalibrateSpectrum):
        CalibrateSpectrum.setObjectName("CalibrateSpectrum")
        CalibrateSpectrum.resize(741, 611)
        self.gridLayout = QtWidgets.QGridLayout(CalibrateSpectrum)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(CalibrateSpectrum)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.spectrum_plot_widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrum_plot_widget.sizePolicy().hasHeightForWidth())
        self.spectrum_plot_widget.setSizePolicy(sizePolicy)
        self.spectrum_plot_widget.setObjectName("spectrum_plot_widget")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calibration_points = QtWidgets.QTableView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_points.sizePolicy().hasHeightForWidth())
        self.calibration_points.setSizePolicy(sizePolicy)
        self.calibration_points.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.calibration_points.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.calibration_points.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.calibration_points.setObjectName("calibration_points")
        self.calibration_points.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.calibration_points)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.point_is_star = QtWidgets.QCheckBox(self.groupBox)
        self.point_is_star.setObjectName("point_is_star")
        self.gridLayout_2.addWidget(self.point_is_star, 1, 0, 1, 5)
        self.remove_calibration_point = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/remove_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_calibration_point.setIcon(icon)
        self.remove_calibration_point.setObjectName("remove_calibration_point")
        self.gridLayout_2.addWidget(self.remove_calibration_point, 3, 4, 1, 1)
        self.wavelength_pick = QtWidgets.QPushButton(self.groupBox)
        self.wavelength_pick.setObjectName("wavelength_pick")
        self.gridLayout_2.addWidget(self.wavelength_pick, 2, 4, 1, 1)
        self.x_axis_pick = QtWidgets.QPushButton(self.groupBox)
        self.x_axis_pick.setFlat(False)
        self.x_axis_pick.setObjectName("x_axis_pick")
        self.gridLayout_2.addWidget(self.x_axis_pick, 0, 4, 1, 1)
        self.set_dispersion = QtWidgets.QPushButton(self.groupBox)
        self.set_dispersion.setObjectName("set_dispersion")
        self.gridLayout_2.addWidget(self.set_dispersion, 4, 4, 1, 1)
        self.dispersion = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dispersion.setDecimals(4)
        self.dispersion.setObjectName("dispersion")
        self.gridLayout_2.addWidget(self.dispersion, 4, 1, 1, 3)
        self.add_calibration_point = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/add_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_calibration_point.setIcon(icon1)
        self.add_calibration_point.setObjectName("add_calibration_point")
        self.gridLayout_2.addWidget(self.add_calibration_point, 3, 3, 1, 1)
        self.point_wavelength = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_wavelength.sizePolicy().hasHeightForWidth())
        self.point_wavelength.setSizePolicy(sizePolicy)
        self.point_wavelength.setDecimals(3)
        self.point_wavelength.setMinimum(0.0)
        self.point_wavelength.setMaximum(1e+26)
        self.point_wavelength.setObjectName("point_wavelength")
        self.gridLayout_2.addWidget(self.point_wavelength, 2, 1, 1, 3)
        self.point_x_axis = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point_x_axis.sizePolicy().hasHeightForWidth())
        self.point_x_axis.setSizePolicy(sizePolicy)
        self.point_x_axis.setMaximum(99999999)
        self.point_x_axis.setObjectName("point_x_axis")
        self.gridLayout_2.addWidget(self.point_x_axis, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(CalibrateSpectrum)
        QtCore.QMetaObject.connectSlotsByName(CalibrateSpectrum)

    def retranslateUi(self, CalibrateSpectrum):
        _translate = QtCore.QCoreApplication.translate
        CalibrateSpectrum.setWindowTitle(_translate("CalibrateSpectrum", "Calibrate"))
        self.groupBox.setTitle(_translate("CalibrateSpectrum", "New Calibration Point"))
        self.label.setText(_translate("CalibrateSpectrum", "x-axis"))
        self.label_2.setText(_translate("CalibrateSpectrum", "Wavelength (Å)"))
        self.label_3.setText(_translate("CalibrateSpectrum", "Dispersion (Å/pix)"))
        self.point_is_star.setText(_translate("CalibrateSpectrum", "Zero (star)"))
        self.remove_calibration_point.setText(_translate("CalibrateSpectrum", "Remove selected point"))
        self.wavelength_pick.setText(_translate("CalibrateSpectrum", "Pick"))
        self.x_axis_pick.setText(_translate("CalibrateSpectrum", "Pick"))
        self.set_dispersion.setText(_translate("CalibrateSpectrum", "Set dispersion"))
        self.add_calibration_point.setText(_translate("CalibrateSpectrum", "Add calibration point"))

