# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/project_widget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjectWidget(object):
    def setupUi(self, ProjectWidget):
        ProjectWidget.setObjectName("ProjectWidget")
        ProjectWidget.resize(840, 586)
        self.gridLayout = QtWidgets.QGridLayout(ProjectWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(ProjectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.import_image = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_image.setIcon(icon)
        self.import_image.setFlat(True)
        self.import_image.setObjectName("import_image")
        self.horizontalLayout_3.addWidget(self.import_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.calibrate = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plot_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrate.setIcon(icon1)
        self.calibrate.setFlat(True)
        self.calibrate.setObjectName("calibrate")
        self.horizontalLayout_3.addWidget(self.calibrate)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.raw_spectra = QtWidgets.QListView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_spectra.sizePolicy().hasHeightForWidth())
        self.raw_spectra.setSizePolicy(sizePolicy)
        self.raw_spectra.setObjectName("raw_spectra")
        self.gridLayout_2.addWidget(self.raw_spectra, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(ProjectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.open_finished = QtWidgets.QPushButton(self.groupBox_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new_open_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_finished.setIcon(icon2)
        self.open_finished.setFlat(True)
        self.open_finished.setObjectName("open_finished")
        self.horizontalLayout_2.addWidget(self.open_finished)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.finished_spectra = QtWidgets.QListView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finished_spectra.sizePolicy().hasHeightForWidth())
        self.finished_spectra.setSizePolicy(sizePolicy)
        self.finished_spectra.setObjectName("finished_spectra")
        self.gridLayout_4.addWidget(self.finished_spectra, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(ProjectWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.math = QtWidgets.QPushButton(self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/math_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.math.setIcon(icon3)
        self.math.setFlat(True)
        self.math.setObjectName("math")
        self.horizontalLayout.addWidget(self.math)
        self.finish = QtWidgets.QPushButton(self.groupBox_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/done_20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finish.setIcon(icon4)
        self.finish.setFlat(True)
        self.finish.setObjectName("finish")
        self.horizontalLayout.addWidget(self.finish)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.calibrated_spectra = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrated_spectra.sizePolicy().hasHeightForWidth())
        self.calibrated_spectra.setSizePolicy(sizePolicy)
        self.calibrated_spectra.setObjectName("calibrated_spectra")
        self.gridLayout_3.addWidget(self.calibrated_spectra, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 2, 1, 1)
        self.equipment = QtWidgets.QLabel(ProjectWidget)
        self.equipment.setObjectName("equipment")
        self.gridLayout.addWidget(self.equipment, 2, 0, 1, 4)
        self.date = QtWidgets.QLabel(ProjectWidget)
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 1, 3, 1, 1)
        self.position = QtWidgets.QLabel(ProjectWidget)
        self.position.setObjectName("position")
        self.gridLayout.addWidget(self.position, 1, 2, 1, 1)
        self.observer = QtWidgets.QLabel(ProjectWidget)
        self.observer.setObjectName("observer")
        self.gridLayout.addWidget(self.observer, 1, 0, 1, 2)
        self.name = QtWidgets.QLabel(ProjectWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 2, 1, 1)

        self.retranslateUi(ProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(ProjectWidget)

    def retranslateUi(self, ProjectWidget):
        _translate = QtCore.QCoreApplication.translate
        ProjectWidget.setWindowTitle(_translate("ProjectWidget", "Form"))
        self.groupBox.setTitle(_translate("ProjectWidget", "Raw Spectra"))
        self.import_image.setText(_translate("ProjectWidget", "Import Image"))
        self.calibrate.setText(_translate("ProjectWidget", "Calibrate"))
        self.groupBox_3.setTitle(_translate("ProjectWidget", "Finished Spectra"))
        self.open_finished.setText(_translate("ProjectWidget", "Open"))
        self.groupBox_2.setTitle(_translate("ProjectWidget", "Calibrated Spectra"))
        self.math.setText(_translate("ProjectWidget", "Math"))
        self.finish.setText(_translate("ProjectWidget", "Finish"))
        self.equipment.setText(_translate("ProjectWidget", "Equipment"))
        self.date.setText(_translate("ProjectWidget", "Date"))
        self.position.setText(_translate("ProjectWidget", "Position"))
        self.observer.setText(_translate("ProjectWidget", "Observer"))
        self.name.setText(_translate("ProjectWidget", "Name"))

